#!/bin/bash

msg_trap() {
	echo "Não pode sair desta forma"
}	

trap msg_trap SIGNIT SIGTERM

semestre() {
	mes=$(date "+%m")
	if(( mes < 7 )); then
		echo "1"
	else	
		echo "2"
	fi
}

ano = $(date "+%Y")
dia = $(date "+%d")
mes = $(date "+%B")
hora = $(date "+%H")
minutos = $(date "+%M")

menu() {
	echo "################################################################"
	
		

	echo "################################################################"
}	


while true; do
	menu
	read -r opcao

	case $opcao in
		1)
			#codigo da opcao interativa aqui
			;;
		2)	

			#mesmo
			;;
		3)
			#mesmo
			;;
		4) 
			#mesmo
			;;
		*)
			echo "opção inválida, tente novamente"
			;;
	esac
done	




